{ inputs, ... }:

# The mutableInputs aspect provides a mechanism for flake-based dotfile
# management that supports live-editing without rebuilds.
#
# When enabled on a host, flake inputs registered as mutable are:
#   1. Cloned as working copies to `root/<name>/`
#   2. Kept in sync with the consumer's flake.lock pin (rebase strategy)
#   3. Made available via .mutable/flake.nix for transparent local eval
#
# Aspects use `config.lib.mutableInputs.link ./path` which transparently
# returns either a mutable symlink (if enabled) or the readonly nix store
# path (if disabled).
#
# The consumer repo commits a passthrough .mutable/flake.nix that re-exports
# the parent flake's outputs. On activation, this file is rewritten with
# git+file:// overrides pointing at local working copies, and VCS is
# configured to ignore the local modifications (jj snapshot.auto-track /
# git skip-worktree). This means `nix build .mutable#...` uses local
# working copies while `nix build .#...` uses locked remote inputs.
#
# Usage (in a consuming flake like jakewoods):
#
#   # Host config enables and configures:
#   local.mutableInputs.enable = true;
#   local.mutableInputs.root = "${config.home.homeDirectory}/work";
#   local.mutableInputs.lockFlake = inputs.self;
#
#   # Register inputs you want mutable:
#   local.mutableInputs.inputs.jakewoods.flakeInput = inputs.self;
#   local.mutableInputs.inputs.devbox-public.flakeInput = inputs.devbox-public;
#
#   # In any aspect, link files:
#   xdg.configFile."doom".source = config.lib.mutableInputs.link ./doom.d;
#
# Upstream repos can declare optional mutable deps (inert unless consumer
# enables mutableInputs):
#
#   local.mutableInputs.inputs.nixpkgs.flakeInput = lib.mkDefault inputs.nixpkgs;
#
{
  flake.aspects = { aspects, ... }: {
    mutableInputs = {
      description = "Mutable working copies of flake inputs for live-edit dotfiles";

      homeManager = { config, lib, pkgs, ... }:
      let
        cfg = config.local.mutableInputs;

        # Read the lock file from the consuming flake (if lockFlake is set)
        # to derive clone URLs and pinned revs for registered inputs.
        lockData =
          if cfg.lockFlake != null
          then builtins.fromJSON
            (builtins.readFile (cfg.lockFlake.outPath + "/flake.lock"))
          else { nodes = {}; };

        # Resolve an input name to its lock file node, following the root
        # input mapping (handles renamed nodes like "nixpkgs_2").
        lockNodeFor = name:
          let
            rootInputs = lockData.nodes.root.inputs or {};
            nodeName = rootInputs.${name} or name;
          in
            if builtins.isString nodeName
            then lockData.nodes.${nodeName} or null
            else null;

        # Derive a flake ref string from the lock file's "original" entry.
        # Used as the argument to `nix flake clone` for initial clones.
        cloneUrlFor = name:
          let
            node = lockNodeFor name;
            original = if node != null then (node.original or null) else null;
          in
            if original != null
            then builtins.flakeRefToString original
            else null;

        # Get the pinned rev from the lock file's "locked" entry.
        pinnedRevFor = name:
          let
            node = lockNodeFor name;
          in
            if node != null then (node.locked.rev or null) else null;

        # The sync script with git/nix paths substituted in.
        syncScript = pkgs.replaceVars ./sync.sh {
          git = "${pkgs.git}/bin/git";
          nix = "${pkgs.nix}/bin/nix";
        };

        # Identify which registered inputs are NOT the consumer itself (i.e.
        # not self). These are the inputs we override in .mutable/flake.nix.
        # The consumer repo's own input (typically "jakewoods") has
        # flakeInput == inputs.self, and its working copy IS the repo that
        # contains .mutable/ — so it's represented by `real.url = "path:.."`.
        selfInputName = lib.findFirst
          (name: toString cfg.inputs.${name}.flakeInput == toString cfg.lockFlake)
          null
          (lib.attrNames cfg.inputs);

        overrideInputs = lib.filterAttrs
          (name: _: name != selfInputName)
          cfg.inputs;

        # Generate the .mutable/flake.nix content with git+file:// overrides.
        mutableFlakeContent =
          let
            inputDecls = lib.concatMapStringsSep "\n"
              (name: "    ${name}.url = \"git+file://${cfg.root}/${name}\";")
              (lib.attrNames overrideInputs);
            followsDecls = lib.concatMapStringsSep "\n"
              (name: "    real.inputs.${name}.follows = \"${name}\";")
              (lib.attrNames overrideInputs);
          in ''
# Auto-generated by mutableInputs. Do not edit manually.
# Regenerated on each home-manager activation.
# Use: nix build .mutable#homeConfigurations.<host>.activationPackage
{
  inputs = {
    real.url = "path:..";
${inputDecls}
${followsDecls}
  };
  outputs = { real, ... }: real.outputs;
}
'';

        # Path to the .mutable directory in the consumer repo.
        # The consumer repo is identified by looking for the self input's
        # working copy location.
        consumerRepoPath =
          if selfInputName != null
          then "${cfg.root}/${selfInputName}"
          else null;

        # The link function: given a nix path, determines which registered
        # input it belongs to and returns either a mutable symlink or the
        # store path.
        link = path:
          let
            pathStr = toString path;
            # Find which registered input this path belongs to by checking
            # which flakeInput's toString is a prefix of the path.
            matchingInput = lib.findFirst
              (name:
                let inputStr = toString cfg.inputs.${name}.flakeInput;
                in lib.hasPrefix inputStr pathStr)
              null
              (lib.attrNames cfg.inputs);
          in
            if !cfg.enable then path
            else if matchingInput == null then path
            else
              let
                relativePath = lib.removePrefix
                  (toString cfg.inputs.${matchingInput}.flakeInput)
                  pathStr;
              in
                config.lib.file.mkOutOfStoreSymlink
                  "${cfg.root}/${matchingInput}${relativePath}";

      in {
        options.local.mutableInputs = {
          enable = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = ''
              Whether to enable mutable working copies for dotfile sources.
              When false, all mutableInputs config is inert: link returns
              store paths, no repos are cloned, no .mutable/ is generated.
              Upstream repos can declare optional mutable deps which are
              harmlessly ignored when this is false.
            '';
          };

          root = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = ''
              Absolute path to the directory containing mutable repo clones.
              Each registered input is expected at <root>/<inputName>/.
              Required when enable = true.
            '';
            example = "/home/user/work";
          };

          lockFlake = lib.mkOption {
            type = lib.types.nullOr lib.types.raw;
            default = null;
            description = ''
              The root flake whose flake.lock is used to derive clone URLs
              and pinned revs for registered inputs. Typically set to
              inputs.self by the consuming flake.
            '';
          };

          inputs = lib.mkOption {
            type = lib.types.attrsOf (lib.types.submodule ({ name, ... }: {
              options = {
                flakeInput = lib.mkOption {
                  type = lib.types.raw;
                  description = ''
                    The flake input this entry corresponds to. Used for:
                    - link function prefix matching (toString gives store path)
                    - Determining clone URL from lockFlake's flake.lock
                  '';
                };
              };
            }));
            default = {};
            description = ''
              Flake inputs to make available as mutable working copies.
              The attrset key is used as the directory name under root.
            '';
          };
        };

        config = {
          assertions = [
            {
              assertion = cfg.enable -> cfg.root != "";
              message = ''
                local.mutableInputs.root must be set when local.mutableInputs.enable is true.
                Set it to the directory containing your mutable repo clones, e.g.:
                  local.mutableInputs.root = "''${config.home.homeDirectory}/work";
              '';
            }
            {
              assertion = cfg.enable -> consumerRepoPath != null;
              message = ''
                local.mutableInputs: cannot determine consumer repo path.
                Ensure one of your mutableInputs.inputs has flakeInput = inputs.self
                (pointing to the flake that contains .mutable/).
              '';
            }
          ];

          # Expose the link function unconditionally so aspects can call it
          # regardless of whether mutableInputs is enabled on the current host.
          lib.mutableInputs = { inherit link; };

          # Clone/sync repos + generate .mutable/flake.nix on activation.
          home.activation.mutableInputsSync = lib.mkIf cfg.enable
            (lib.hm.dag.entryBetween [ "linkGeneration" ] [ "writeBoundary" ]
              (let
                # Clone/sync commands for each input.
                syncCommands = lib.concatStringsSep "\n"
                  (lib.mapAttrsToList (name: _inputCfg:
                    let
                      cloneUrl = cloneUrlFor name;
                      rev = pinnedRevFor name;
                      dest = "${cfg.root}/${name}";
                    in
                      if cloneUrl == null then ''
                        # --- ${name}: no clone URL available ---
                        if [ ! -d ${lib.escapeShellArg dest} ]; then
                          echo "mutableInputs: WARNING: ${name} not found at ${dest} and no clone URL derivable from flake.lock. Skipping."
                        fi
                      ''
                      else ''
                        # --- ${name}: sync ---
                        ${pkgs.bash}/bin/bash ${syncScript} ${lib.escapeShellArg dest} ${lib.escapeShellArg cloneUrl} ${lib.optionalString (rev != null) (lib.escapeShellArg rev)}
                      ''
                  ) cfg.inputs);

                mutableDir = "${consumerRepoPath}/.mutable";
                git = "${pkgs.git}/bin/git";

                # Generate .mutable/flake.nix with local overrides.
                # The .mutable/ directory is:
                #   - Listed in the parent repo's .gitignore (invisible to jj/git)
                #   - Has its own .git (so nix can see flake.nix via git index)
                # This gives us `nix build .mutable#...` that uses local working
                # copies, while the parent repo's VCS stays permanently clean.
                mutableGenCommands = ''
                  # --- Ensure .mutable/ is its own git repo ---
                  mkdir -p ${lib.escapeShellArg mutableDir}
                  if [ ! -d ${lib.escapeShellArg "${mutableDir}/.git"} ]; then
                    ${git} -C ${lib.escapeShellArg mutableDir} init 2>/dev/null
                  fi

                  # --- Generate .mutable/flake.nix with local overrides ---
                  cat > ${lib.escapeShellArg "${mutableDir}/flake.nix"} << 'MUTABLE_FLAKE_EOF'
${mutableFlakeContent}
MUTABLE_FLAKE_EOF

                  # --- Commit so nix sees a clean source tree (no dirty warning) ---
                  ${git} -C ${lib.escapeShellArg mutableDir} add flake.nix
                  ${git} -C ${lib.escapeShellArg mutableDir} diff --cached --quiet 2>/dev/null \
                    || ${git} -C ${lib.escapeShellArg mutableDir} commit -m "mutableInputs: update overrides" --quiet 2>/dev/null || true
                '';
              in
                syncCommands + "\n" + mutableGenCommands));
        };
      };
    };
  };
}
